package com.generatedsources.wsdl.fedex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-06T22:57:59.204-07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://fedex.com/ws/track/v10", name = "TrackPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TrackPortType {

    @WebMethod(action = "http://fedex.com/ws/track/v10/sendNotifications")
    @WebResult(name = "SendNotificationsReply", targetNamespace = "http://fedex.com/ws/track/v10", partName = "SendNotificationsReply")
    public SendNotificationsReply sendNotifications(
        @WebParam(partName = "SendNotificationsRequest", name = "SendNotificationsRequest", targetNamespace = "http://fedex.com/ws/track/v10")
        SendNotificationsRequest sendNotificationsRequest
    );

    @WebMethod(action = "http://fedex.com/ws/track/v10/sendSignatureProofOfDeliveryFax")
    @WebResult(name = "SignatureProofOfDeliveryFaxReply", targetNamespace = "http://fedex.com/ws/track/v10", partName = "SignatureProofOfDeliveryFaxReply")
    public SignatureProofOfDeliveryFaxReply sendSignatureProofOfDeliveryFax(
        @WebParam(partName = "SignatureProofOfDeliveryFaxRequest", name = "SignatureProofOfDeliveryFaxRequest", targetNamespace = "http://fedex.com/ws/track/v10")
        SignatureProofOfDeliveryFaxRequest signatureProofOfDeliveryFaxRequest
    );

    @WebMethod(action = "http://fedex.com/ws/track/v10/retrieveSignatureProofOfDeliveryLetter")
    @WebResult(name = "SignatureProofOfDeliveryLetterReply", targetNamespace = "http://fedex.com/ws/track/v10", partName = "SignatureProofOfDeliveryLetterReply")
    public SignatureProofOfDeliveryLetterReply retrieveSignatureProofOfDeliveryLetter(
        @WebParam(partName = "SignatureProofOfDeliveryLetterRequest", name = "SignatureProofOfDeliveryLetterRequest", targetNamespace = "http://fedex.com/ws/track/v10")
        SignatureProofOfDeliveryLetterRequest signatureProofOfDeliveryLetterRequest
    );

    @WebMethod(action = "http://fedex.com/ws/track/v10/track")
    @WebResult(name = "TrackReply", targetNamespace = "http://fedex.com/ws/track/v10", partName = "TrackReply")
    public TrackReply track(
        @WebParam(partName = "TrackRequest", name = "TrackRequest", targetNamespace = "http://fedex.com/ws/track/v10")
        TrackRequest trackRequest
    );
}
